version: '3.8'

services:
  server_1:
    build: .
    ports:
      - 6000:6000
    environment:
      SERVER_ID: 1
      PYTHONUNBUFFERED: 1
  server_2:
    build: .
    ports:
      - 7000:6000
    environment:
      SERVER_ID: 2
      PYTHONUNBUFFERED: 1